# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return []
  end
  pods_vers = []
  File.foreach(file_abs_path) do |line|
    next if line.strip.empty? or line.strip[0] == "#"
    key, value = line.strip.split(separator)
    if value.nil?
      value = ''
    end
    pods_vers.push({key: key, value: value})
  end
  return pods_vers
end

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting the file and running flutter pub get again."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  # Prefer static frameworks for Flutter plugins to avoid runtime issues
  use_frameworks! :linkage => :static

  install_all_flutter_pods(flutter_root)
end

post_install do |installer|
  flutter_post_install(installer)
end
